FROM tomcat:9.0
RUN apt-get update && apt-get install default-jdk maven git -y
WORKDIR /
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
WORKDIR /boxfuse-sample-java-war-hello
RUN mvn package
RUN mkdir /home/app
RUN cp /boxfuse-sample-java-war-hello/target/hello-1.0.war /home/app/ROOT.war
